version: "1.0"
services:
  db:
    container_name: "dsh_db_users"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dsh_db_users
    ports:
      - "5441:5432"
    networks:
      - custom
  db_test:
    container_name: "dsh_db_users_test"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres_test
      - POSTGRES_PASSWORD=postgres_test
      - POSTGRES_DB=dsh_db_users_test
    ports:
      - "5442:5432"
    networks:
      - custom
networks:
  custom:
    driver: bridge